---
- name: Test for k3s binary
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin


# Throws errors but still joins cluster ok. We will wait a minute then check if its running
- name: k3s binary missing
  when: not k3s_bin.stat.exists
  delegate_to: localhost
  become_user: "{{ lookup('env', 'USER') }}"
  block:
  - name: Install k3s
    shell: k3sup join --server --server-user {{ ansible_user }} \
            --server-ip {{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}
            --user {{ ansible_user }} --ip {{ ansible_default_ipv4.address }} \
            {{ k3sup_extra_args | default('') }} {{ k3s_server_extra_args | default('') }}
    args:
      warn: False
    ignore_errors: True

  - name: Let HA master start up
    pause:
      minutes: 1

- name: Make sure k3s started on HA masters
  systemd:
    state: started
    name: k3s

