---
- name: Test for k3s binary
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin

# Single master config
- name: k3s binary missing
  when: not k3s_bin.stat.exists
  delegate_to: localhost
  become_user: "{{ lookup('env', 'USER') }}"
  block:
  - name: Install k3s single master
    shell: k3sup install {{ kube_config_args }} \
            --user {{ ansible_user }} --ip {{ ansible_default_ipv4.address }} \
            {{ k3sup_extra_args | default('') }} {{ k3s_server_extra_args | default('') }}
    when: groups['masters'] | length == 1

  # Multiple HA masters config
  - name: Install k3s - first HA master
    shell: k3sup install --cluster {{ kube_config_args }} \
            --user {{ ansible_user }} --ip {{ ansible_default_ipv4.address }} \
            {{ k3sup_extra_args | default('') }} {{ k3s_server_extra_args | default('') }}
    when: groups['masters'] | length > 1
