---
- name: Generate random password if not provided
  set_fact:
    pi_pass: "{{ lookup('password', '/dev/null length=30') }}"
  delegate_to: localhost
  run_once: yes
  when: not pi_pass

- name: Update pi user password
  user:
    name: pi
    password: "{{ pi_pass | password_hash('sha512') }}"

- name: Print password
  debug:
    msg: "New password: {{ pi_pass }}"
  delegate_to: localhost
  run_once: yes
