---
- name: Test for k3s binary
  stat:
    path: /usr/local/bin/k3s
  register: k3s_bin

- name: Install k3s
  delegate_to: localhost
  become_user: "{{ lookup('env', 'USER') }}"
  shell: k3sup join --server-user {{ ansible_user }} \
          --server-ip {{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }} \
          --user {{ ansible_user }} --ip {{ ansible_default_ipv4.address }} \
          {{ k3sup_extra_args | default('') }}
  when: not k3s_bin.stat.exists
