---
- name: Ensure hostname set
  hostname:
    name: "{{ inventory_hostname }}"
  register: hostname

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Reduce gpu memory
  lineinfile:
    path: /boot/config.txt
    regexp: "gpu_mem"
    line: gpu_mem=16
  register: gpu_mem

- name: Activating cgroup
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^(.*rootwait)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  register: boot_cmdline

- name: Reboot
  reboot:
    msg: "Ansible Reboot"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: hostname is changed or gpu_mem is changed or boot_cmdline is changed
