---
- name: Fetch kubeconfig file
  delegate_to: localhost
  become_user: "{{ lookup('env', 'USER') }}"
  shell: k3sup install --skip-install {{ kube_config_args }} \
          --user {{ ansible_user }} --ip {{ ansible_default_ipv4.address }}
